### ISSUE TITLE
Wrong contact in case of multiple interfaces

### ISSUE THREAD

**Issue by negbie** [cloudwebrtc/go-sip-ua#54]
func (s SipStack) GetNetworkInfo(protocol string) *transport.Target

Just uses util.ResolveSelfIP() for the contact address. I would suggest to change it into:

```Go
	var target transport.Target
	if s.host != "" {
		target.Host = s.host
	} else if v, err := util.ResolveSelfIP(); err == nil {
		target.Host = v.String()
	} else {
		logger.Panicf("resolve host IP failed: %s", err)
	}

```

**Comment by cloudwebrtc** [comment]
I still have no idea, can we fix it before Send?
https://github.com/cloudwebrtc/go-sip-ua/blob/master/pkg/stack/stack.go#L426

**Comment by negbie** [comment]
Do you think it has more advantages to do it inside the Send func instead of adding the above written condition here https://github.com/cloudwebrtc/go-sip-ua/blob/master/pkg/stack/stack.go#L306

**Comment by cloudwebrtc** [comment]
Yeah, we first set the contact to `sip:localhost`. In the Send func, modify the contact to `sip:127.0.0.1:5060;transport=udp` or `sip:192.168.1.xxx:5062;transport=tcp` according to the interface selected (According to msg.Destination) when sending out, This way you can get the correct local address on the contact URI. 

@ghettovoice Do you have better suggestions?

**Comment by ghettovoice** [comment]
In my current app I'm using user agent instance per account (usually provided through the config).
So actually one user agent handles requests for a single contact registered with a provided account.  
Contact port is resolved from account params matching selected transport to defined sip listeners, so it will have correct port (by default using udp transport and udp listener port ). Host is taken from a config, for example if we have domain name, or auto-resolved with `util.ResolveSelfIP()`.  

So finally I have a user agent bound to some contact and all session establish/update requests sent through it have correct Contact header. As I remember I was inspired similar approach in the [baresip](https://github.com/baresip/baresip) user agent implementation.

**Comment by negbie** [comment]
> Contact port is resolved from account params matching selected transport to defined sip listeners, so it will have correct port (by default using udp transport and udp listener port )

For me this does not work. I have two interfaces 
eth0 with IP 192.168.4.1
eth1 with IP 10.1.6.8
I use:
stack := stack.NewSipStack(&stack.SipStackConfig{Host:"10.1.6.8"})
and the listen address listen := "10.1.6.8:6000"

Contact for my case is 192.168.4.1:6000. Thats why I suggested to use the host variable in GetNetworkInfo.

**Comment by ghettovoice** [comment]
Yes, I have a `host` key in the config too. Usually when a server has related domain name. If it is empty, then host addr will be resolved from available interfaces (that is usually 192.168....) or through STUN if it was enabled.
And then when I build a contact inside user agent:
1. I use resolved host addr that is resolved and stored inside user agent. 
2. port is resolved from a sip listeners config and account transport param (that is udp by default). 

Regarding listeners: I just listen on all interfaces with "0.0.0.0:port_num" - where port_num is taken from a sip ports map.

Here is my  simplified config:

```
host: 10.1.6.8 # force to this addr, if empty auto resolve with STUN or from local interfaces
stun: true/false # use or not STUN during host auto-resolving
sip_ports:
    udp: 5060
    tcp: 5060
    tls: 5061
    ws: 5062
    wss: 5063
accounts:
    # account credentials and params
    # credentials is used during registration
    - user: ...
       password: ...
       host: .... # host addr of registrar
       params:
           transport: tls # if empty - use udp port, else use port of defined transport
....
```

I hope it is more clear
